name: zine
description: A TikTok App Clone

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^0.10.1+3
  cached_network_image: ^2.2.0+1
  http: ^0.12.0+2
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.6
  image_picker: ^0.6.7+3
  timeago: ^2.0.26
  firebase_auth: ^0.16.1
  uuid: ^2.2.0
  path_provider: ^1.6.11
  firebase_messaging: ^6.0.16
  firebase_storage: ^3.1.6
  geolocator: ^5.3.2+2
  flutter_launcher_icons: ^0.7.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpeg"

dev_dependencies:
  flutter_test:
    sdk: flutter
    

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family:  TikTokIcons
      fonts:
        - asset: assets/fonts/TikTokIcons.ttf
